-- Seed roles and permissions. The bootstrap admin user is created in Java
-- (com.attendance.identity.service.AdminBootstrapper) so the bcrypt hash
-- is generated by the configured PasswordEncoder rather than embedded as a literal.

SET @now = UTC_TIMESTAMP();

-- ---------- roles ----------
SET @role_admin    = UNHEX(REPLACE(UUID(), '-', ''));
SET @role_hr       = UNHEX(REPLACE(UUID(), '-', ''));
SET @role_manager  = UNHEX(REPLACE(UUID(), '-', ''));
SET @role_employee = UNHEX(REPLACE(UUID(), '-', ''));

INSERT INTO role (id, name, description, is_system, created_at, updated_at, version) VALUES
    (@role_admin,    'ADMIN',      'Full system administrator', TRUE, @now, @now, 0),
    (@role_hr,       'HR_MANAGER', 'HR / organization manager', TRUE, @now, @now, 0),
    (@role_manager,  'MANAGER',    'Team manager (scope-limited)', TRUE, @now, @now, 0),
    (@role_employee, 'EMPLOYEE',   'Standard employee', TRUE, @now, @now, 0);

-- ---------- permissions ----------
INSERT INTO permission (id, code, description, created_at, updated_at, version) VALUES
    (UNHEX(REPLACE(UUID(),'-','')), 'user.read',        'View users', @now, @now, 0),
    (UNHEX(REPLACE(UUID(),'-','')), 'user.write',       'Create / edit users', @now, @now, 0),
    (UNHEX(REPLACE(UUID(),'-','')), 'role.read',        'View roles', @now, @now, 0),
    (UNHEX(REPLACE(UUID(),'-','')), 'role.write',       'Assign / edit roles', @now, @now, 0),
    (UNHEX(REPLACE(UUID(),'-','')), 'audit.read',       'View audit log', @now, @now, 0),
    (UNHEX(REPLACE(UUID(),'-','')), 'system.admin',     'System administration (settings, backups, retention)', @now, @now, 0),
    (UNHEX(REPLACE(UUID(),'-','')), 'employee.read',    'View employees', @now, @now, 0),
    (UNHEX(REPLACE(UUID(),'-','')), 'employee.write',   'Create / edit employees', @now, @now, 0),
    (UNHEX(REPLACE(UUID(),'-','')), 'schedule.read',    'View schedules', @now, @now, 0),
    (UNHEX(REPLACE(UUID(),'-','')), 'schedule.write',   'Create / edit schedules', @now, @now, 0),
    (UNHEX(REPLACE(UUID(),'-','')), 'timecard.read',    'View time cards', @now, @now, 0),
    (UNHEX(REPLACE(UUID(),'-','')), 'timecard.edit',    'Manually edit time cards / punches', @now, @now, 0),
    (UNHEX(REPLACE(UUID(),'-','')), 'leave.read',       'View leave requests', @now, @now, 0),
    (UNHEX(REPLACE(UUID(),'-','')), 'leave.approve',    'Approve / reject leave', @now, @now, 0),
    (UNHEX(REPLACE(UUID(),'-','')), 'report.run',       'Generate / download reports', @now, @now, 0),
    (UNHEX(REPLACE(UUID(),'-','')), 'ingestion.write',  'Submit ingestion punches via JWT', @now, @now, 0),
    (UNHEX(REPLACE(UUID(),'-','')), 'device.read',      'View devices and ingestion sources', @now, @now, 0),
    (UNHEX(REPLACE(UUID(),'-','')), 'device.write',     'Create / edit devices and ingestion sources', @now, @now, 0),
    (UNHEX(REPLACE(UUID(),'-','')), 'exception.read',   'View exceptions', @now, @now, 0),
    (UNHEX(REPLACE(UUID(),'-','')), 'exception.resolve','Resolve exceptions', @now, @now, 0);

-- ADMIN: every permission.
INSERT INTO role_permission (role_id, permission_id)
SELECT @role_admin, p.id FROM permission p;

INSERT INTO role_permission (role_id, permission_id)
SELECT @role_hr, p.id FROM permission p
WHERE p.code IN ('user.read','employee.read','employee.write','schedule.read','schedule.write',
                 'timecard.read','timecard.edit','leave.read','leave.approve','report.run',
                 'exception.read','exception.resolve','audit.read');

INSERT INTO role_permission (role_id, permission_id)
SELECT @role_manager, p.id FROM permission p
WHERE p.code IN ('employee.read','schedule.read','timecard.read','timecard.edit',
                 'leave.read','leave.approve','report.run','exception.read','exception.resolve');

INSERT INTO role_permission (role_id, permission_id)
SELECT @role_employee, p.id FROM permission p
WHERE p.code IN ('timecard.read','leave.read');
